@startuml

participant "**Application**" as C1a93a7ca
participant "**ClassA**" as C38afe297
participant "1fd14d74\n(**ClassA**)" as O1fd14d74

[->C1a93a7ca:Application.gogo(..)
C1a93a7ca->C38afe297:Application.ClassA(..)
C38afe297->C38afe297:Application.ClassA.<clinit>
C38afe297->O1fd14d74:Application.ClassA(..)
O1fd14d74->O1fd14d74:Application.ClassA.name
O1fd14d74-->C38afe297
C38afe297-->C1a93a7ca
C1a93a7ca->O1fd14d74:Application.ClassA.methodA(..)
O1fd14d74->O1fd14d74:Application.ClassA.methodB(..)
O1fd14d74-->C1a93a7ca
C1a93a7ca-->[

@enduml